services:
  car-tracking:
    build: .
    image: car-tracking:latest
    stop_grace_period: 30s
    env_file:
      - .env
    environment:
      HEADLESS_MODE: "True"
      RTSP_URL: ${RTSP_URL:-/app/videos/traffic_1.mp4}
      OMP_NUM_THREADS: "8"
      OPENBLAS_NUM_THREADS: "8"
      MKL_NUM_THREADS: "8"
      VECLIB_MAXIMUM_THREADS: "8"
      NUMEXPR_NUM_THREADS: "8"
    volumes:
      - ./artifacts:/app/artifacts
    extra_hosts:
      - "host.docker.internal:host-gateway"